import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import {
  AiGenerateRequest,
  AiGenerateResponse,
  buildJournalistPrompt,
  isAiToolType,
} from '@/lib/ai/journalistPrompts';
import { formatTranscriptionForMinutes } from '@/lib/export/formatTranscriptionForMinutes';
import { aiConfig, pipelineConfig } from '@/lib/config';
import { requireAuth } from '@/lib/auth-utils';

export async function POST(request: NextRequest): Promise<NextResponse<AiGenerateResponse>> {
  const startTime = Date.now();

  // Check authentication
  const authResult = await requireAuth();
  if (!authResult.authorized) {
    return authResult.response as NextResponse<AiGenerateResponse>;
  }

  try {
    // Validate API key
    if (!aiConfig.GEMINI_API_KEY) {
      return NextResponse.json(
        {
          success: false,
          error: 'Gemini API key is not configured',
        },
        { status: 500 }
      );
    }

    // Parse request body
    const body: AiGenerateRequest = await request.json();

    // Validate request
    if (!body.segments || !Array.isArray(body.segments)) {
      return NextResponse.json(
        {
          success: false,
          error: 'Missing or invalid segments array',
        },
        { status: 400 }
      );
    }

    if (!isAiToolType(body.type)) {
      return NextResponse.json(
        {
          success: false,
          error: 'Missing or invalid tool type',
        },
        { status: 400 }
      );
    }

    // Format transcription text for the prompt
    const transcriptionText = formatTranscriptionForMinutes(body.segments);

    // Build the full prompt
    const prompt = buildJournalistPrompt(body.type, transcriptionText, {
      language: body.language,
    });

    // Initialize Gemini client
    const client = new GoogleGenAI({ apiKey: aiConfig.GEMINI_API_KEY });

    // Generate content using Gemini
    const response = await client.models.generateContent({
      model: pipelineConfig.geminiModel,
      contents: [
        {
          role: 'user',
          parts: [{ text: prompt }],
        },
      ],
      config: {
        maxOutputTokens: 4096,
        temperature: 0.4,
      },
    });

    // Extract the generated text
    const generatedText = response.text || '';

    if (!generatedText) {
      return NextResponse.json(
        {
          success: false,
          error: 'No content generated by the AI model',
        },
        { status: 500 }
      );
    }

    const processingTimeMs = Date.now() - startTime;

    return NextResponse.json({
      success: true,
      markdown: generatedText,
      processingTimeMs,
    });
  } catch (error) {
    console.error('[AI Generate] Error:', error);

    const errorMessage = error instanceof Error ? error.message : 'Failed to generate content';

    return NextResponse.json(
      {
        success: false,
        error: errorMessage,
        processingTimeMs: Date.now() - startTime,
      },
      { status: 500 }
    );
  }
}
