import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import { PressReleaseRequest, PressReleaseResponse } from '@/lib/export/pressReleaseTypes';
import { buildPressReleasePrompt } from '@/lib/export/pressReleasePrompt';
import { formatTranscriptionForMinutes } from '@/lib/export/formatTranscriptionForMinutes';
import { aiConfig } from '@/lib/config';
import { requireAuth } from '@/lib/auth-utils';

export async function POST(request: NextRequest): Promise<NextResponse<PressReleaseResponse>> {
  const startTime = Date.now();

  // Check authentication
  const authResult = await requireAuth();
  if (!authResult.authorized) {
    return authResult.response as NextResponse<PressReleaseResponse>;
  }

  try {
    // Validate API key
    if (!aiConfig.GEMINI_API_KEY) {
      return NextResponse.json(
        {
          success: false,
          error: 'Gemini API key is not configured',
        },
        { status: 500 }
      );
    }

    // Parse request body
    const body: PressReleaseRequest = await request.json();

    // Validate request
    if (!body.segments || !Array.isArray(body.segments)) {
      return NextResponse.json(
        {
          success: false,
          error: 'Missing or invalid segments array',
        },
        { status: 400 }
      );
    }

    if (!body.metadata) {
      return NextResponse.json(
        {
          success: false,
          error: 'Missing metadata object',
        },
        { status: 400 }
      );
    }

    // Format transcription text for the prompt
    const transcriptionText = formatTranscriptionForMinutes(body.segments);

    // Build the full prompt
    const prompt = buildPressReleasePrompt(body.metadata, transcriptionText);

    // Initialize Gemini client
    const client = new GoogleGenAI({ apiKey: aiConfig.GEMINI_API_KEY });

    // Generate press release using Gemini
    const response = await client.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: [
        {
          role: 'user',
          parts: [{ text: prompt }],
        },
      ],
      config: {
        maxOutputTokens: 4096, // Press releases are shorter
        temperature: 0.3, // Slightly more creative than official minutes
      },
    });

    // Extract the generated text
    const generatedText = response.text || '';

    if (!generatedText) {
      return NextResponse.json(
        {
          success: false,
          error: 'No content generated by the AI model',
        },
        { status: 500 }
      );
    }

    const processingTimeMs = Date.now() - startTime;

    return NextResponse.json({
      success: true,
      markdown: generatedText,
      processingTimeMs,
    });
  } catch (error) {
    console.error('[Press Release Export] Error:', error);

    const errorMessage = error instanceof Error ? error.message : 'Failed to generate press release';

    return NextResponse.json(
      {
        success: false,
        error: errorMessage,
        processingTimeMs: Date.now() - startTime,
      },
      { status: 500 }
    );
  }
}
