import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import { OfficialMinutesRequest, OfficialMinutesResponse } from '@/lib/export/types';
import { buildOfficialMinutesPrompt } from '@/lib/export/officialMinutesPrompt';
import { formatTranscriptionForMinutes } from '@/lib/export/formatTranscriptionForMinutes';
import { aiConfig } from '@/lib/config';

export async function POST(request: NextRequest): Promise<NextResponse<OfficialMinutesResponse>> {
  const startTime = Date.now();

  try {
    // Validate API key
    if (!aiConfig.GEMINI_API_KEY) {
      return NextResponse.json(
        {
          success: false,
          error: 'Gemini API key is not configured',
        },
        { status: 500 }
      );
    }

    // Parse request body
    const body: OfficialMinutesRequest = await request.json();

    // Validate request
    if (!body.segments || !Array.isArray(body.segments)) {
      return NextResponse.json(
        {
          success: false,
          error: 'Missing or invalid segments array',
        },
        { status: 400 }
      );
    }

    if (!body.metadata) {
      return NextResponse.json(
        {
          success: false,
          error: 'Missing metadata object',
        },
        { status: 400 }
      );
    }

    // Format transcription text for the prompt
    const transcriptionText = formatTranscriptionForMinutes(body.segments);

    // Build the full prompt
    const prompt = buildOfficialMinutesPrompt(body.metadata, transcriptionText);

    // Initialize Gemini client
    const client = new GoogleGenAI({ apiKey: aiConfig.GEMINI_API_KEY });

    // Generate official minutes using Gemini
    const response = await client.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: [
        {
          role: 'user',
          parts: [{ text: prompt }],
        },
      ],
      config: {
        maxOutputTokens: 16384,
        temperature: 0.2, // Low temperature for formal, consistent output
      },
    });

    // Extract the generated text
    const generatedText = response.text || '';

    if (!generatedText) {
      return NextResponse.json(
        {
          success: false,
          error: 'No content generated by the AI model',
        },
        { status: 500 }
      );
    }

    const processingTimeMs = Date.now() - startTime;

    return NextResponse.json({
      success: true,
      markdown: generatedText,
      processingTimeMs,
    });
  } catch (error) {
    console.error('[Official Minutes Export] Error:', error);

    const errorMessage = error instanceof Error ? error.message : 'Failed to generate official minutes';

    return NextResponse.json(
      {
        success: false,
        error: errorMessage,
        processingTimeMs: Date.now() - startTime,
      },
      { status: 500 }
    );
  }
}
